---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gfs-nvme-pvc-share-{{ .Values.NameSpace }} # 修改用户名
  namespace: {{ .Values.NameSpace }} # 修改命名空间
spec:
  storageClassName: kadalu.gfs-nvme-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T # 与上面PV保持一致避免浪费
