{{ $uid := .Values.UIDD | default "1000" }}
{{ $gid := .Values.GIDD | default "1000" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uidgidcm
  namespace: {{ .Values.NameSpace }}
data:
  gid: '{{ .Values.NameSpace }}:x:{{ $gid }}:'
  uid: '{{ .Values.NameSpace }}:x:{{ $uid }}:{{ $gid }}:{{ .Values.NameSpace }}:/:/sbin/nologin'
