apiVersion: mellanox.com/v1alpha1
kind: IPoIBNetwork
metadata:
  name: ipoibnetwork-{{ .Values.NameSpace }}
spec:
  networkNamespace: {{ .Values.NameSpace }}
  master: "ibs121"
  ipam: |
    {
      "type": "whereabouts",
      "datastore": "kubernetes",
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"
      },
      "range": "192.168.0.0/16",
      "log_file" : "/var/log/whereabouts.log",
      "log_level" : "info",
      "gateway": "192.168.0.1"
    }