---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-ns-binding
  namespace: {{ .Values.NameSpace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.EMAIL }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-user-pv-{{ .Values.NameSpace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole-user-pv
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.EMAIL }}