---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfshome-{{ .Values.NameSpace }}
  namespace: {{ .Values.NameSpace }}
spec:
  storageClassName: nfs-users
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T  # 申请的资源大小
---
apiVersion: v1
kind: Endpoints
metadata: #元数据
  name: gfs-sata-ep-svc-share-{{ .Values.NameSpace }} #ep名称
  namespace: {{ .Values.NameSpace }} #命名空间
subsets: #配置glusterfs连接信息
- addresses: #添加glusterfs分布式地址
  - ip: 10.3.0.2
  - ip: 10.3.0.3
  - ip: 10.3.0.4
  - ip: 10.3.0.5
  - ip: 10.3.0.6
  - ip: 10.3.0.7
  - ip: 10.3.0.8
  - ip: 10.3.0.9
  - ip: 10.3.0.10
  - ip: 10.3.0.11
  - ip: 10.3.0.12
  - ip: 10.3.0.13
  - ip: 10.3.0.14
  - ip: 10.3.0.15
  - ip: 10.3.0.16
  - ip: 10.3.0.17
  - ip: 10.3.0.18
  - ip: 10.3.0.19
  - ip: 10.3.0.20
  - ip: 10.3.0.21
  - ip: 10.3.0.22
  - ip: 10.3.0.23
  - ip: 10.3.0.24
  - ip: 10.3.0.25
  - ip: 10.3.0.26
  - ip: 10.3.0.27
  - ip: 10.3.0.28
  - ip: 10.3.0.29
  ports: #设定glusterfs服务端口 可以修改任意端口号
  - port: 1990
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gfs-sata-ep-svc-share-{{ .Values.NameSpace }} #服务名称
  # 需要修改
  namespace: {{ .Values.NameSpace }} #命名空间
spec:
  ports:
  - port: 1990
    protocol: TCP
    targetPort: 1990 # 与ep的端口保持一致
  sessionAffinity: None #是否支持session
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-sata-pv-share-{{ .Values.NameSpace }} # 修改用户名{{ .Values.NameSpace }}
spec:
  capacity:
    storage: 15T # 与下面PVC保持一致避免浪费
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: "gfs-sata-ep-svc-share-{{ .Values.NameSpace }}"
    # 与glusterfs_endpoints_server.yaml中的name保持一致
    path: "gfsvol02/share"
    # 需要先在gfs中创建此路径，不然会报错
    # 如果K8S中报错提示路径不存在，只需要在gfs中补充创建此路径后重启k8s的pod即可修复
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gfs-sata-pvc-share-{{ .Values.NameSpace }} # 修改用户名
  namespace: {{ .Values.NameSpace }} # 修改命名空间
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15T # 与上面PV保持一致避免浪费
