---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfshome-{{ .Values.NameSpace }}
  namespace: {{ .Values.NameSpace }}
spec:
  storageClassName: nfs-users
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T  # 申请的资源大小
